# Google Cloud Build configuration for ASL-to-Text AI
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/asl-to-text-ai', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/asl-to-text-ai']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'asl-to-text-ai'
    - '--image'
    - 'gcr.io/$PROJECT_ID/asl-to-text-ai'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300'

images:
  - 'gcr.io/$PROJECT_ID/asl-to-text-ai'
