services:
  - type: web
    name: asl-to-text-ai-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: python app_simple.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /api/health
